Repository crowbar/crowbar-openstack, pull requests merged in 2018-08, with the labels that each got.

#1720 neutron: add force_metadata attribute
  chef/cookbooks/neutron/recipes/network_agents.rb
  chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
  chef/data_bags/crowbar/migrate/neutron/210_add_force_metadata_attributes.rb
  chef/data_bags/crowbar/template-neutron.json
  chef/data_bags/crowbar/template-neutron.schema
Labels: needs backport to SOC7

#1722 [4.0] Neutron force metadata feature backend
  chef/cookbooks/neutron/recipes/network_agents.rb
  chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
  chef/data_bags/crowbar/migrate/neutron/118_add_force_metadata_attributes.rb
  chef/data_bags/crowbar/template-neutron.json
  chef/data_bags/crowbar/template-neutron.schema
Labels: backport from SOC8

#1732 Synchronize SSL in the cluster (bsc#1081518)
  chef/cookbooks/horizon/recipes/server.rb
Labels: bug, needs backport to SOC7, needs backport to SOC8

#1734 [4.0] Synchronize SSL in the cluster (bsc#1081518)
  chef/cookbooks/horizon/recipes/server.rb
Labels: backport from SOC9, bug

#1735 [5.0] Synchronize SSL in the cluster (bsc#1081518)
  chef/cookbooks/horizon/recipes/server.rb
Labels: backport from SOC9, bug

#1727 nova: reload nova-placement-api (bsc#1103383)
  chef/cookbooks/nova/recipes/config.rb
Labels: bug, needs backport to SOC7, needs backport to SOC8

#1728 [4.0] nova: reload nova-placement-api (bsc#1103383)
  chef/cookbooks/nova/recipes/config.rb
Labels: backport from SOC9, bug

#1736 Heat: Make non-founder HA nodes do less work
  chef/cookbooks/heat/recipes/server.rb
Labels: needs backport to SOC7, needs backport to SOC8

#1742 [5.0] Heat: Make non-founder HA nodes do less work
  chef/cookbooks/heat/recipes/server.rb
Labels: backport from SOC9

#1723 rabbitmq: fix extra users password regeneration
  crowbar_framework/app/models/rabbitmq_service.rb
Labels: needs backport to SOC7

#1724 [4.0] rabbitmq: fix extra users password regeneration
  crowbar_framework/app/models/rabbitmq_service.rb
Labels: backport from SOC8

#1733 keystone: Fix missing keystone migration (bsc#1104182)
  chef/data_bags/crowbar/migrate/keystone/114_remove_updated_password.rb
  chef/data_bags/crowbar/template-keystone.json
Labels: backport from SOC8, bug

#1744 [4.0] glance: Fix ironic related glance code
  chef/cookbooks/glance/recipes/api.rb
Labels: backport from SOC8

#1743 [4.0] Heat: Make non-founder HA nodes do less work
  chef/cookbooks/heat/recipes/server.rb
Labels: backport from SOC9

#1748 neutron: Increase wait_neutron-agents_ha_resources timeout
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: needs backport to SOC7

#1746 [4.0] split database-server role into backend specific roles
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
  chef/cookbooks/database/attributes/default.rb
  chef/cookbooks/database/libraries/crowbar.rb
  chef/cookbooks/database/libraries/database_library.rb
  chef/cookbooks/database/recipes/role_database_server.rb
  chef/cookbooks/database/recipes/role_mysql_server.rb
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/recipes/server.rb
  chef/cookbooks/postgresql/recipes/ha.rb
  chef/cookbooks/postgresql/recipes/ha_storage.rb
  chef/cookbooks/postgresql/recipes/server.rb
  chef/cookbooks/postgresql/recipes/server_debian.rb
  chef/cookbooks/postgresql/recipes/server_redhat.rb
  chef/data_bags/crowbar/migrate/database/109_separate_db_roles.rb
  chef/data_bags/crowbar/template-database.json
  chef/data_bags/crowbar/template-database.schema
  chef/roles/database-server.rb
  chef/roles/mysql-server.rb
  crowbar_framework/app/helpers/barclamp/database_helper.rb
  crowbar_framework/app/models/database_service.rb
  crowbar_framework/app/models/monasca_service.rb
  crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml
  crowbar_framework/config/locales/database/en.yml
Labels: upgrade
