Repository crowbar/crowbar-openstack, pull requests merged in 2018-06, with the labels that each got.

#1680 upgrade: cinder: run live migrations at correct rev
  chef/cookbooks/cinder/recipes/sql.rb
Labels: upgrade

#1677 Add rate limiting for glance api (bsc#1005886)
  chef/cookbooks/glance/recipes/ha.rb
  chef/data_bags/crowbar/migrate/glance/202_add_rate_limit.rb
  chef/data_bags/crowbar/template-glance.json
  chef/data_bags/crowbar/template-glance.schema
Labels: needs backport to SOC7

#1687 [4.0] Add rate limiting for glance api (bsc#1005886)
  chef/cookbooks/glance/recipes/ha.rb
  chef/data_bags/crowbar/migrate/glance/105_add_rate_limit.rb
  chef/data_bags/crowbar/template-glance.json
  chef/data_bags/crowbar/template-glance.schema
Labels: backport from SOC8

#1674 aodh: Add config for alarm_history_ttl (bsc#1073703)
  chef/cookbooks/aodh/attributes/default.rb
  chef/cookbooks/aodh/recipes/aodh.rb
  chef/cookbooks/aodh/templates/default/aodh.conf.erb
  chef/data_bags/crowbar/migrate/aodh/202_add_alarm_history_ttl.rb
  chef/data_bags/crowbar/template-aodh.json
  chef/data_bags/crowbar/template-aodh.schema
  crowbar_framework/app/views/barclamp/aodh/_edit_attributes.html.haml
  crowbar_framework/config/locales/aodh/en.yml
Labels: needs backport to SOC7

#1675 Add elasticsearch tunables
  chef/cookbooks/monasca/recipes/master.rb
  chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
  chef/data_bags/crowbar/migrate/monasca/204_add_elasticsearch_tunables.rb
  chef/data_bags/crowbar/template-monasca.json
  chef/data_bags/crowbar/template-monasca.schema
Labels: needs backport to SOC7

#1692 manila: Correct field name for cluster name
  crowbar_framework/app/views/barclamp/manila/_edit_attributes.html.haml
  crowbar_framework/config/locales/manila/en.yml
Labels: needs backport to SOC7
