Repository crowbar/crowbar-openstack, pull requests merged in 2018-07, with the labels that each got.

#1682 Fix monasca installer
  chef/cookbooks/monasca/recipes/master.rb
  chef/cookbooks/monasca/templates/default/run-monasca-installer.erb
Labels: needs backport to SOC7

#1396 rabbitmq: Make sure rabbitmq is running on cluster HA
  chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
Labels: needs backport to SOC7

#1697 [4.0] rabbitmq: Make sure rabbitmq is running on cluster HA
  chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
Labels: backport from SOC8, do not merge yet

#1706 Do not automatically put manila-share roles to compute nodes
  crowbar_framework/app/models/manila_service.rb
Labels: needs forward-port to SOC8, upgrade

#1709 Do not automatically put manila-share roles to compute nodes
  crowbar_framework/app/models/manila_service.rb
Labels: forward-port from SOC7

#1713 [4.0] split database-server role into backend specific roles
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
  chef/cookbooks/database/attributes/default.rb
  chef/cookbooks/database/libraries/crowbar.rb
  chef/cookbooks/database/libraries/database_library.rb
  chef/cookbooks/database/recipes/role_database_server.rb
  chef/cookbooks/database/recipes/role_mysql_server.rb
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/recipes/server.rb
  chef/cookbooks/postgresql/recipes/ha.rb
  chef/cookbooks/postgresql/recipes/ha_storage.rb
  chef/cookbooks/postgresql/recipes/server.rb
  chef/cookbooks/postgresql/recipes/server_debian.rb
  chef/cookbooks/postgresql/recipes/server_redhat.rb
  chef/data_bags/crowbar/migrate/database/109_separate_db_roles.rb
  chef/data_bags/crowbar/template-database.json
  chef/data_bags/crowbar/template-database.schema
  chef/roles/database-server.rb
  chef/roles/mysql-server.rb
  crowbar_framework/app/helpers/barclamp/database_helper.rb
  crowbar_framework/app/models/database_service.rb
  crowbar_framework/app/models/monasca_service.rb
  crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml
  crowbar_framework/config/locales/database/en.yml
Labels: upgrade

#1719 [4.0] Revert split database-server role into backend specific roles
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
  chef/cookbooks/database/attributes/default.rb
  chef/cookbooks/database/libraries/crowbar.rb
  chef/cookbooks/database/libraries/database_library.rb
  chef/cookbooks/database/recipes/role_database_server.rb
  chef/cookbooks/database/recipes/server.rb
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/recipes/server.rb
  chef/cookbooks/postgresql/recipes/ha.rb
  chef/cookbooks/postgresql/recipes/ha_storage.rb
  chef/cookbooks/postgresql/recipes/server.rb
  chef/cookbooks/postgresql/recipes/server_debian.rb
  chef/cookbooks/postgresql/recipes/server_redhat.rb
  chef/data_bags/crowbar/migrate/database/109_separate_db_roles.rb
  chef/data_bags/crowbar/template-database.json
  chef/data_bags/crowbar/template-database.schema
  chef/roles/database-server.rb
  chef/roles/mysql-server.rb
  crowbar_framework/app/helpers/barclamp/database_helper.rb
  crowbar_framework/app/models/database_service.rb
  crowbar_framework/app/models/monasca_service.rb
  crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml
  crowbar_framework/config/locales/database/en.yml
Labels: upgrade

#1714 rabbitmq: set client timout to default value
  chef/data_bags/crowbar/template-rabbitmq.json
Labels: needs backport to SOC7

#1715 [4.0] rabbitmq: set client timout to default value
  chef/data_bags/crowbar/template-rabbitmq.json
Labels: backport from SOC7

#1703 [4.0] copytruncate apache logs instead of creating
  chef/cookbooks/horizon/templates/default/openstack-dashboard.logrotate.erb
Labels: backport from SOC8
