Repository crowbar/crowbar-openstack, pull requests merged in 2018-04, with the labels that each got.

#1616 keystone: Increase WSGI request timeout to 10 minutes
  chef/cookbooks/keystone/recipes/server.rb
Labels: bug, needs backport to SOC7

#1363 tempest: remove world-readable permission from tempest.conf
  chef/cookbooks/tempest/recipes/config.rb
Labels: needs backport to SOC6, needs backport to SOC7

#1620 keystone: Increase WSGI request timeout to 10 minutes
  chef/cookbooks/keystone/recipes/server.rb
Labels: backport from SOC8, bug

#1622 mysql: Set monitor to 10s for galera-python-clustercheck
  chef/cookbooks/mysql/recipes/ha_galera.rb
Labels: backport from SOC8

#1623 nova: disable progress timeout for live migration
  chef/cookbooks/nova/templates/default/nova.conf.erb
Labels: backport from SOC8

#1583 Fixes needed for adding a node into existing cluster
  chef/cookbooks/neutron/recipes/common_agent.rb
  crowbar_framework/app/models/cinder_service.rb
  crowbar_framework/lib/openstack/ha.rb
Labels: needs backport to SOC7

#1626 [4.0] Fixes needed for adding a node into existing cluster
  chef/cookbooks/neutron/recipes/common_agent.rb
  crowbar_framework/app/models/cinder_service.rb
  crowbar_framework/lib/openstack/ha.rb
Labels: backport from SOC8

#1469 Keystone LDAP speedup
  chef/cookbooks/crowbar-openstack/templates/default/vhost-wsgi.conf.erb
  chef/cookbooks/horizon/templates/centos/local_settings.py.erb
  chef/cookbooks/horizon/templates/centos/openstack-dashboard.conf.erb
  chef/cookbooks/horizon/templates/default/openstack-dashboard.conf.erb
  chef/cookbooks/horizon/templates/redhat/local_settings.py.erb
  chef/cookbooks/horizon/templates/redhat/openstack-dashboard.conf.erb
  chef/cookbooks/keystone/templates/centos/apache_keystone.conf.erb
  chef/cookbooks/keystone/templates/redhat/apache_keystone.conf.erb
  chef/data_bags/crowbar/template-keystone.json
Labels: needs backport to SOC7

#1632 rabbitmq: restart epmd on config change
  chef/cookbooks/rabbitmq/recipes/default.rb
Labels: upgrade

#1637 rabbitmq: Do not check if service is running when it is not supposed to run
  chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
Labels: upgrade

#1645 upgrade: Keep mariadb running at all nodes during the upgrade
  chef/cookbooks/mysql/recipes/ha_galera.rb
Labels: upgrade
