Repository crowbar/crowbar-openstack, pull requests merged in 2018-11, with the labels that each got.

#1872 [5.0] Fix migrations
  chef/data_bags/crowbar/migrate/neutron/111_remove_use_lbaasv2.rb
  chef/data_bags/crowbar/migrate/neutron/112_add_back_use_l2pop.rb
  chef/data_bags/crowbar/migrate/rabbitmq/002_ha.rb
Labels: backport from SOC9

#1873 [4.0] Fix migrations
  chef/data_bags/crowbar/migrate/neutron/120_remove_use_lbaasv2.rb
  chef/data_bags/crowbar/migrate/neutron/121_add_back_use_l2pop.rb
  chef/data_bags/crowbar/migrate/rabbitmq/002_ha.rb
  chef/data_bags/crowbar/template-neutron.json
Labels: backport from SOC9

#1875 [5.0] Travis: Validate databags
  .travis.yml
  Gemfile
Labels: backport from SOC9

#1876 [4.0] Travis: Validate databags
  .travis.yml
  Gemfile
Labels: backport from SOC9

#1865 rabbitmq: block client port on startup
  chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq-alert-handler.erb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq-port-blocker.erb
Labels: forward-port from SOC8

#1868 Add list of tags comma separated for extra users
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
Labels: needs backport to SOC7, needs backport to SOC8

#1837 change deprecated options from rocky
  chef/cookbooks/aodh/templates/default/aodh.conf.erb
  chef/cookbooks/barbican/templates/default/barbican.conf.erb
  chef/cookbooks/ceilometer/templates/default/ceilometer.conf.erb
  chef/cookbooks/cinder/templates/default/cinder.conf.erb
  chef/cookbooks/ec2-api/templates/default/ec2api.conf.erb
  chef/cookbooks/glance/templates/default/glance-api.conf.erb
  chef/cookbooks/glance/templates/default/glance-registry.conf.erb
  chef/cookbooks/glance/templates/default/glance-scrubber.conf.erb
  chef/cookbooks/heat/templates/default/heat.conf.erb
  chef/cookbooks/ironic/templates/default/ironic.conf.erb
  chef/cookbooks/keystone/templates/default/keystone.conf.erb
  chef/cookbooks/magnum/templates/default/magnum.conf.erb
  chef/cookbooks/manila/templates/default/manila.conf.erb
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
  chef/cookbooks/nova/templates/default/nova.conf.erb
  chef/cookbooks/sahara/templates/default/sahara.conf.erb
  chef/cookbooks/swift/templates/default/proxy-server.conf.erb
Labels: do not merge yet

#1826 neutron: disable metadata proxy when metadata is forced
  chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
  chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
Labels: needs backport to SOC7, needs backport to SOC8

#1843 [4.0] neutron: disable metadata proxy when metadata is forced
  chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
  chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
Labels: backport from SOC9

#1844 [5.0] neutron: disable metadata proxy when metadata is forced
  chef/cookbooks/neutron/templates/default/dhcp_agent.ini.erb
  chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
Labels: backport from SOC9

#1726 [4.0] neutron/nova: allow overriding default_log_levels
  chef/cookbooks/neutron/recipes/common_config.rb
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
  chef/cookbooks/nova/recipes/config.rb
  chef/cookbooks/nova/templates/default/nova.conf.erb
  chef/data_bags/crowbar/migrate/neutron/122_add_default_log_levels.rb
  chef/data_bags/crowbar/migrate/nova/125_add_default_log_levels.rb
  chef/data_bags/crowbar/template-neutron.json
  chef/data_bags/crowbar/template-neutron.schema
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
Labels: backport from SOC9

#1883 rabbitmq: Add list of tags comma separated for extra users
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
Labels: backport from SOC8, backport from SOC9

#1882 rabbitmq: Add list of tags comma separated for extra users
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
Labels: backport from SOC9

#1889 Fix "enable_metadata_proxy" setting for DVR setups
  chef/cookbooks/neutron/recipes/common_agent.rb
  chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
Labels: needs backport to SOC7, needs backport to SOC8

#1891 [4.0] neutron: Fix "enable_metadata_proxy" setting for DVR setups
  chef/cookbooks/neutron/recipes/common_agent.rb
  chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
Labels: backport from SOC9

#1867 neutron: disable metering agent if no ceilometer
  chef/cookbooks/neutron/recipes/network_agents.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: needs backport to SOC7, needs backport to SOC8
