Repository crowbar/crowbar-openstack, pull requests merged in 2018-09, with the labels that each got.

#1753 [5.0] neutron: Increase wait_neutron-agents_ha_resources timeout
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: backport from SOC9, upgrade

#1712 database: Drop temporary mysql-server role, used for upgrade only
  chef/data_bags/crowbar/migrate/database/209_merge_db_roles.rb
  chef/data_bags/crowbar/template-database.json
Labels: needs backport to SOC8, upgrade

#1755 [5.0] database: Drop temporary mysql-server role, used for upgrade only
  chef/data_bags/crowbar/migrate/database/209_merge_db_roles.rb
  chef/data_bags/crowbar/template-database.json
Labels: backport from SOC9, upgrade

#1759 /etc/sysctl.d/99-sysctl.conf is a symlink to /etc/sysctl.conf
  chef/cookbooks/neutron/recipes/network_agents.rb
Labels: backport from SOC8

#1747 rabbitmq: allow tuning tcpnodelay and keepalive
  chef/data_bags/crowbar/template-rabbitmq.json
  chef/data_bags/crowbar/template-rabbitmq.schema
Labels: needs backport to SOC7, needs backport to SOC8

#1741 [4.0] keystone: Always try to rsync keys to new nodes
  chef/cookbooks/horizon/recipes/ha.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/nova/recipes/controller_ha.rb
Labels: upgrade

#1754 Correct configuration of DRBD resources in 3-node cluster
  chef/cookbooks/crowbar-openstack/definitions/openstack_pacemaker_drbd_controller_only_location_for.rb
  chef/cookbooks/crowbar-openstack/libraries/ha_helpers.rb
  chef/cookbooks/postgresql/recipes/ha.rb
  chef/cookbooks/postgresql/recipes/ha_storage.rb
  chef/cookbooks/rabbitmq/recipes/ha.rb
Labels: upgrade

#1769 database: Hide SSL options from database UI
  crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml
Labels: do not merge yet

#1705 [4.0] database: UI for mysql and/or postgresql
  crowbar_framework/app/assets/javascripts/barclamps/database/application.js
  crowbar_framework/app/models/database_service.rb
  crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml
  crowbar_framework/config/locales/database/en.yml
Labels: upgrade

#1757 [5.0] keystone: Always try to rsync keys to new nodes
  chef/cookbooks/horizon/recipes/ha.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/nova/recipes/controller_ha.rb
Labels: forward-port from SOC7, upgrade

#1758 keystone: Always try to rsync keys to new nodes
  chef/cookbooks/horizon/recipes/ha.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/nova/recipes/controller_ha.rb
Labels: forward-port from SOC7, upgrade

#1763 database: Prepare mysql database for data migration
  bin/prepare-mariadb
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
  chef/cookbooks/database/libraries/crowbar.rb
  chef/cookbooks/database/recipes/pg2mariadb_preparation.rb
  chef/cookbooks/database/templates/default/mariadb-databases.yaml.erb
  chef/cookbooks/database/templates/default/mariadb-override.conf.erb
  chef/cookbooks/horizon/recipes/server.rb
  chef/cookbooks/horizon/templates/default/local_settings.py.erb
Labels: upgrade

#1785 [5.0] keystone: Fix retry behavior on password update
  chef/cookbooks/keystone/providers/register.rb
Labels: backport from SOC9

#1786 [4.0] keystone: Fix retry behavior on password update
  chef/cookbooks/keystone/providers/register.rb
Labels: backport from SOC9

#1787 [4.0] Fernet keys sync polish
  chef/cookbooks/keystone/recipes/ha.rb
  chef/cookbooks/keystone/recipes/server.rb
Labels: backport from SOC8, upgrade

#1794 [4.0] nova: move flavor creation to converge phase
  chef/cookbooks/nova/recipes/flavors.rb
Labels: backport from SOC8

#1797 [5.0] make notifications optional
  chef/cookbooks/cinder/templates/default/cinder.conf.erb
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
  chef/cookbooks/glance/templates/default/glance-api.conf.erb
  chef/cookbooks/glance/templates/default/glance-registry.conf.erb
  chef/cookbooks/magnum/templates/default/magnum.conf.erb
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
  chef/cookbooks/nova/templates/default/nova.conf.erb
  chef/cookbooks/tempest/recipes/config.rb
  chef/data_bags/crowbar/migrate/rabbitmq/205_add_notifications.rb
  chef/data_bags/crowbar/template-rabbitmq.json
  chef/data_bags/crowbar/template-rabbitmq.schema
  crowbar_framework/app/views/barclamp/rabbitmq/_edit_attributes.html.haml
  crowbar_framework/config/locales/rabbitmq/en.yml
Labels: backport from SOC9, forward-port from SOC7

#1783 Make notifications optional
  chef/cookbooks/cinder/templates/default/cinder.conf.erb
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
  chef/cookbooks/glance/templates/default/glance-api.conf.erb
  chef/cookbooks/glance/templates/default/glance-registry.conf.erb
  chef/cookbooks/magnum/templates/default/magnum.conf.erb
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
  chef/cookbooks/nova/templates/default/nova.conf.erb
  chef/cookbooks/tempest/recipes/config.rb
  chef/data_bags/crowbar/migrate/rabbitmq/301_add_notifications.rb
  chef/data_bags/crowbar/template-rabbitmq.json
  chef/data_bags/crowbar/template-rabbitmq.schema
  crowbar_framework/app/views/barclamp/rabbitmq/_edit_attributes.html.haml
  crowbar_framework/config/locales/rabbitmq/en.yml
Labels: do not merge yet, needs backport to SOC7, needs backport to SOC8

#1776 neutron: Don't assign the aci role to any node by default
  crowbar_framework/app/models/neutron_service.rb
Labels: needs backport to SOC8

#1778 [5.0] neutron: Don't assign the aci role to any node by default
  crowbar_framework/app/models/neutron_service.rb
Labels: backport from SOC9

#1777 [4.0] neutron: Don't assign the aci role to any node by default
  crowbar_framework/app/models/neutron_service.rb
Labels: backport from SOC9

#1729 [5.0] nova: reload nova-placement-api (bsc#1103383)
  chef/cookbooks/nova/recipes/config.rb
Labels: backport from SOC9, bug

#1737 Do not share ports Apache2 and HAProxy (bsc#1105086)
  chef/cookbooks/horizon/recipes/ha.rb
Labels: bug, needs backport to SOC7, needs backport to SOC8

#1739 Do not share ports Apache2 and HAProxy (bsc#1105086)
  chef/cookbooks/horizon/recipes/ha.rb
Labels: backport from SOC9, bug

#1738 Do not share ports Apache2 and HAProxy (bsc#1105086)
  chef/cookbooks/horizon/recipes/ha.rb
Labels: backport from SOC9, bug

#1690 monasca: add elasticsearch tunables (bsc#1090343)
  chef/cookbooks/monasca/recipes/master.rb
  chef/cookbooks/monasca/templates/default/crowbar_vars.yml.erb
  chef/data_bags/crowbar/migrate/monasca/104_add_elasticsearch_tunables.rb
  chef/data_bags/crowbar/template-monasca.json
  chef/data_bags/crowbar/template-monasca.schema
Labels: backport from SOC8

#1801 [5.0] nova: Increase retries for listing flavors
  chef/cookbooks/nova/recipes/flavors.rb
Labels: backport from SOC9

#1802 [4.0] nova: Increase retries for listing flavors
  chef/cookbooks/nova/recipes/flavors.rb
Labels: backport from SOC9
