Repository crowbar/crowbar-openstack, pull requests merged in 2018-10, with the labels that each got.

#1772 [4.0] keystone: Reorganize HA/fernet code
  chef/cookbooks/keystone/providers/fernet.rb
  chef/cookbooks/keystone/recipes/ha.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/keystone/resources/fernet.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
  chef/cookbooks/nova/recipes/controller_ha.rb
Labels: needs forward-port to SOC8, needs forward-port to SOC9, upgrade

#1813 [4.0] neutron: define sql_max_pool_size for config template expansion
  chef/cookbooks/neutron/recipes/common_config.rb
Labels: backport from SOC9, bug

#1803 [5.0] neutron/nova: allow overriding default_log_levels
  chef/cookbooks/neutron/recipes/common_config.rb
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
  chef/cookbooks/nova/recipes/config.rb
  chef/cookbooks/nova/templates/default/nova.conf.erb
  chef/data_bags/crowbar/migrate/neutron/212_add_default_log_levels.rb
  chef/data_bags/crowbar/migrate/nova/210_add_default_log_levels.rb
  chef/data_bags/crowbar/template-neutron.json
  chef/data_bags/crowbar/template-neutron.schema
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
Labels: backport from SOC9

#1762 Neutron: disable metadata agent service if not necessary
  chef/cookbooks/neutron/definitions/neutron_metadata.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: needs backport to SOC7

#1818 [5.0] Neutron: disable metadata agent service if not necessary
  chef/cookbooks/neutron/definitions/neutron_metadata.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: backport from SOC9

#1773 [4.0] Neutron: disable metadata agent service if not necessary
  chef/cookbooks/neutron/definitions/neutron_metadata.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: backport from SOC8

#1825 Neutron force metadata disable metadata agent fix
  chef/cookbooks/neutron/definitions/neutron_metadata.rb
Labels: bug, needs backport to SOC7, needs backport to SOC8

#1830 database: Increase galera write set limits
  chef/cookbooks/mysql/templates/default/galera.cnf.erb
Labels: needs backport to SOC7, needs backport to SOC8

#1822 [5.0] Neutron force metadata disable metadata agent fix
  chef/cookbooks/neutron/definitions/neutron_metadata.rb
Labels: backport from SOC8, bug

#1828 [4.0] database: Fix log line
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
Labels: upgrade

#1832 [4.0]database: Increase galera write set limits
  chef/cookbooks/mysql/templates/default/galera.cnf.erb
Labels: backport from SOC9

#1831 [5.0] database: Increase galera write set limits
  chef/cookbooks/mysql/templates/default/galera.cnf.erb
Labels: backport from SOC9

#1725 neutron/nova: allow overriding default_log_levels
  chef/cookbooks/neutron/recipes/common_config.rb
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
  chef/cookbooks/nova/recipes/config.rb
  chef/cookbooks/nova/templates/default/nova.conf.erb
  chef/data_bags/crowbar/migrate/neutron/302_add_default_log_levels.rb
  chef/data_bags/crowbar/migrate/nova/301_add_default_log_levels.rb
  chef/data_bags/crowbar/template-neutron.json
  chef/data_bags/crowbar/template-neutron.schema
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
Labels: needs backport to SOC7, needs backport to SOC8

#1846 [4.0] postgresql: Add timestamp prefix to logs
  chef/cookbooks/postgresql/attributes/default.rb
Labels: backport from SOC9

#1847 [5.0] postgresql: Add timestamp prefix to logs
  chef/cookbooks/postgresql/attributes/default.rb
Labels: backport from SOC9

#1806 rabbitmq: default to openstack/openstack for new installs
  chef/data_bags/crowbar/template-rabbitmq.json
Labels: needs backport to SOC8

#1807 nova: disable notification reporting when disabled
  chef/cookbooks/nova/templates/default/nova.conf.erb
Labels: needs backport to SOC7, needs backport to SOC8

#1855 ceilometer: add validation that notifications are enabled client side
  crowbar_framework/app/models/ceilometer_service.rb
  crowbar_framework/config/locales/ceilometer/en.yml
Labels: needs backport to SOC7, needs backport to SOC8

#1857 [5.0] rabbitmq: configure notification settings also in clustered mode
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
Labels: backport from SOC9

#1852 [5.0] keystone: Reorganize HA/fernet code
  chef/cookbooks/keystone/providers/fernet.rb
  chef/cookbooks/keystone/recipes/ha.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/keystone/resources/fernet.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
  chef/cookbooks/nova/recipes/controller_ha.rb
Labels: forward-port from SOC7, upgrade

#1853 keystone: Reorganize HA/fernet code
  chef/cookbooks/keystone/providers/fernet.rb
  chef/cookbooks/keystone/recipes/ha.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/keystone/resources/fernet.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
  chef/cookbooks/nova/recipes/controller_ha.rb
Labels: forward-port from SOC7, forward-port from SOC8, upgrade

#1851 [5.0] rabbitmq: Fix address handling in rabbitmq (aka "glance timeout")
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
  chef/cookbooks/crowbar-openstack/metadata.rb
  chef/cookbooks/rabbitmq/attributes/default.rb
  chef/cookbooks/rabbitmq/libraries/crowbar.rb
  chef/cookbooks/rabbitmq/metadata.rb
  chef/cookbooks/rabbitmq/recipes/default.rb
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb
Labels: forward-port from SOC7, upgrade

#1839 [4.0] upgrade: Remove chef-client timeout from prepare-mariadb
  bin/prepare-mariadb
Labels: upgrade

#1808 rabbitmq: allow disabling queue mirroring
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/data_bags/crowbar/template-rabbitmq.json
  chef/data_bags/crowbar/template-rabbitmq.schema
Labels: needs backport to SOC7, needs backport to SOC8

#1864 rabbitmq: Fix address handling in rabbitmq (aka "glance timeout")
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
  chef/cookbooks/crowbar-openstack/metadata.rb
  chef/cookbooks/rabbitmq/attributes/default.rb
  chef/cookbooks/rabbitmq/libraries/crowbar.rb
  chef/cookbooks/rabbitmq/metadata.rb
  chef/cookbooks/rabbitmq/recipes/default.rb
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq.config.erb
Labels: forward-port from SOC7, upgrade

#1681 [5.0] rabbitmq: block client port on startup
  chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq-alert-handler.erb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq-port-blocker.erb
Labels: needs backport to SOC7, needs forward-port to SOC9, upgrade

#1858 [4.0] rabbitmq: configure notification settings also in clustered mode
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
Labels: backport from SOC9

#1809 [5.0] rabbitmq: allow disabling queue mirroring
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/data_bags/crowbar/migrate/rabbitmq/206_add_enable_queue_mirroring.rb
  chef/data_bags/crowbar/template-rabbitmq.json
  chef/data_bags/crowbar/template-rabbitmq.schema
Labels: backport from SOC9

#1810 [4.0] rabbitmq: allow disabling queue mirroring
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/data_bags/crowbar/migrate/rabbitmq/107_add_enable_queue_mirroring.rb
  chef/data_bags/crowbar/template-rabbitmq.json
  chef/data_bags/crowbar/template-rabbitmq.schema
Labels: backport from SOC9

#1870 Fix migrations
  chef/data_bags/crowbar/migrate/keystone/205_remove_updated_password.rb
  chef/data_bags/crowbar/migrate/neutron/111_remove_use_lbaasv2.rb
  chef/data_bags/crowbar/migrate/neutron/112_add_back_use_l2pop.rb
  chef/data_bags/crowbar/migrate/nova/302_remove_xen.rb
  chef/data_bags/crowbar/migrate/rabbitmq/002_ha.rb
  chef/data_bags/crowbar/template-nova.json
Labels: needs backport to SOC6, needs backport to SOC7, needs backport to SOC8

#1841 travis: tests databags
  .travis.yml
  Gemfile
Labels: needs backport to SOC7, needs backport to SOC8

#1874 Gemfile: Drop crowbar-validate-databags gem version
  Gemfile
Labels: needs backport to SOC7, needs backport to SOC8
