Repository crowbar/crowbar-openstack, pull requests merged in 2018-05, with the labels that each got.

#1653 rabbitmq: create empty users list which is expected by some recipes
  chef/cookbooks/rabbitmq/attributes/default.rb
Labels: backport from SOC8

#1554 rabbitmq: block client port on startup
  chef/cookbooks/rabbitmq/files/default/rabbitmq.tmpfiles
  chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
  chef/cookbooks/rabbitmq/templates/default/hacluster_sudoers.erb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq-alert-handler.erb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq-port-blocker.erb
Labels: do not merge yet, needs backport to SOC7

#1563 [4.0] rabbitmq: block client port on startup
  chef/cookbooks/rabbitmq/files/default/rabbitmq.tmpfiles
  chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
  chef/cookbooks/rabbitmq/templates/default/hacluster_sudoers.erb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq-alert-handler.erb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq-port-blocker.erb
Labels: backport from SOC8

#1649 [4.0] tempest: remove world-readable permission from tempest.conf
  chef/cookbooks/tempest/recipes/config.rb
Labels: backport from SOC8

#1646 [4.0] keystone: Add retry loop to _get_token (bsc#1087466)
  chef/cookbooks/keystone/providers/register.rb
Labels: backport from SOC8

#1659 nova: transparent hugepage setting fixes
  chef/cookbooks/nova/recipes/compute.rb
  chef/cookbooks/nova/templates/default/crowbar-compute-set-sys-options.erb
Labels: bug, needs backport to SOC7

#1667 [4.0] transparent hugetable fixes (backport of PR 1659)
  chef/cookbooks/nova/recipes/compute.rb
  chef/cookbooks/nova/templates/default/crowbar-compute-set-sys-options.erb
Labels: backport from SOC8

#1664 Revert "[4.0] rabbitmq: block client port on startup"
  chef/cookbooks/rabbitmq/files/default/rabbitmq.tmpfiles
  chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
  chef/cookbooks/rabbitmq/templates/default/hacluster_sudoers.erb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq-alert-handler.erb
  chef/cookbooks/rabbitmq/templates/default/rabbitmq-port-blocker.erb
Labels: backport from SOC8, revert, upgrade

#1648 nova: After upgrading controller to Pike, map the instances to cell1
  chef/cookbooks/nova/recipes/database.rb
Labels: upgrade

#1668 keystone: avoid race condition during admin password change
  chef/cookbooks/keystone/providers/register.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/keystone/resources/register.rb
Labels: needs backport to SOC7

#1670 [4.0] keystone: avoid race condition during admin password change
  chef/cookbooks/keystone/providers/register.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/keystone/resources/register.rb
Labels: backport from SOC8

#1619 nova: disable progress timeout for live migration (bsc#1091190)
  chef/cookbooks/nova/templates/default/nova.conf.erb
Labels: needs backport to SOC7

#1671 nova: allow to enable nested virt on Intel
  chef/cookbooks/nova/recipes/compute.rb
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
Labels: backport from SOC8, enhancement
