Repository crowbar/crowbar-openstack, pull requests merged in 2018-03, with the labels that each got.

#1354 [4.0] Backport rabbit cleanup
  chef/cookbooks/rabbitmq/recipes/default.rb
Labels: backport from SOC8

#1506 RabbitMQ allow to add extra users to rabbit
  chef/cookbooks/rabbitmq/recipes/default.rb
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/cookbooks/rabbitmq/templates/default/definitions.json.erb
  chef/data_bags/crowbar/migrate/rabbitmq/204_add_extra_users.rb
  chef/data_bags/crowbar/template-rabbitmq.json
  chef/data_bags/crowbar/template-rabbitmq.schema
  crowbar_framework/app/models/rabbitmq_service.rb
  crowbar_framework/app/views/barclamp/rabbitmq/_edit_attributes.html.haml
  crowbar_framework/config/locales/rabbitmq/en.yml
Labels: needs backport to SOC7

#1278 rabbitmq: do not create the erlang cookie file
  chef/cookbooks/rabbitmq/attributes/default.rb
  chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
Labels: needs backport to SOC7

#1511 [4.0] Rabbitmq allow to add extra users to rabbit backport
  chef/cookbooks/rabbitmq/recipes/default.rb
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/cookbooks/rabbitmq/templates/default/definitions.json.erb
  chef/data_bags/crowbar/migrate/rabbitmq/105_add_extra_users.rb
  chef/data_bags/crowbar/template-rabbitmq.json
  chef/data_bags/crowbar/template-rabbitmq.schema
  crowbar_framework/app/models/rabbitmq_service.rb
  crowbar_framework/app/views/barclamp/rabbitmq/_edit_attributes.html.haml
  crowbar_framework/config/locales/rabbitmq/en.yml
Labels: backport from SOC8

#1576 [4.0] rabbitmq: do not create the erlang cookie file on cluster deployment
  chef/cookbooks/rabbitmq/attributes/default.rb
  chef/cookbooks/rabbitmq/recipes/ha_cluster.rb
Labels: backport from SOC8

#1578 nova: Add option to modify scheduler's enabled_filters
  chef/cookbooks/nova/recipes/config.rb
  chef/cookbooks/nova/templates/default/nova.conf.erb
  chef/data_bags/crowbar/migrate/nova/208_add_scheduler_enabled_filters.rb
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
Labels: forward-port from SOC7

#1475 neutron: Put ML2 Cisco config files as snippets in neutron.conf.d
  chef/cookbooks/neutron/attributes/default.rb
  chef/cookbooks/neutron/recipes/cisco_apic_support.rb
  chef/cookbooks/neutron/recipes/cisco_support.rb
  chef/cookbooks/neutron/recipes/server.rb
Labels: needs backport to SOC7

#1582 [4.0] neutron: enable automatic lbaas reschedule
  chef/cookbooks/neutron/recipes/network_agents.rb
  chef/cookbooks/neutron/templates/default/lbaas_agent.ini.erb
  chef/data_bags/crowbar/migrate/neutron/116_add_allow_automatic_lbass_agent_failover.rb
  chef/data_bags/crowbar/template-neutron.json
  chef/data_bags/crowbar/template-neutron.schema
Labels: backport from SOC8

#1579 rabbitmq: allow pacemaker restart
  chef/cookbooks/rabbitmq/recipes/default.rb
Labels: needs backport to SOC7

#1584 memcached: Disable UDP by default (bsc#1083903)
  chef/cookbooks/memcached/templates/default/memcached.sysconfig.erb
Labels: bug, needs backport to SOC6, needs backport to SOC7

#1589 [4.0] memcached: Disable UDP by default (bsc#1083903)
  chef/cookbooks/memcached/templates/default/memcached.sysconfig.erb
Labels: backport from SOC8

#1590 memcached: Disable UDP by default (bsc#1083903)
  chef/cookbooks/memcached/templates/default/memcached.sysconfig.erb
Labels: backport from SOC8

#1580 [4.0] rabbitmq: allow pacemaker service restart
  chef/cookbooks/rabbitmq/recipes/default.rb
Labels: backport from SOC8

#1585 [4.0] swift: Fix switch detection (bsc#1075015)
  chef/cookbooks/swift/libraries/rack_awareness.rb
Labels: backport from SOC8

#1593 barbican: Add missing roles used in policy.json (bsc#1081573)
  chef/cookbooks/barbican/recipes/api.rb
Labels: needs backport to SOC7

#1569 [4.0] barbican: Add creator role (bsc#1081573)
  chef/cookbooks/barbican/recipes/api.rb
Labels: backport from SOC8

#1574 horizon: fix apache logrotate
  chef/cookbooks/horizon/templates/default/openstack-dashboard.logrotate.erb
Labels: needs backport to SOC7

#1601 Revert "rabbitmq: allow pacemaker restart"
  chef/cookbooks/rabbitmq/recipes/default.rb
Labels: needs backport to SOC7

#1602 Revert "[4.0] rabbitmq: allow pacemaker service restart"
  chef/cookbooks/rabbitmq/recipes/default.rb
Labels: backport from SOC8

#1596 [4.0] Backport Nova Placement API
  chef/cookbooks/nova/attributes/default.rb
  chef/cookbooks/nova/definitions/nova_package.rb
  chef/cookbooks/nova/recipes/config.rb
  chef/cookbooks/nova/recipes/controller_ha.rb
  chef/cookbooks/nova/recipes/database.rb
  chef/cookbooks/nova/recipes/placement_api.rb
  chef/cookbooks/nova/recipes/role_nova_controller.rb
  chef/cookbooks/nova/templates/default/nova-placement.conf.erb
  chef/data_bags/crowbar/migrate/nova/123_placement_api.rb
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
  crowbar_framework/app/models/nova_service.rb
Labels: do not merge yet

#1542 [3.0] swift: Standalone proxies contain swift-account
  chef/cookbooks/swift/recipes/auth.rb
  chef/cookbooks/swift/recipes/proxy.rb
  chef/cookbooks/swift/recipes/storage.rb
Labels: backport from SOC8
