Repository crowbar/crowbar-openstack, pull requests merged in 2018-12, with the labels that each got.

#1860 ironic: Use ironic network for provisioning (bsc#1108398)
  chef/cookbooks/ironic/recipes/server.rb
  chef/cookbooks/ironic/templates/default/ironic.conf.erb
Labels: needs backport to SOC8

#1924 ironic: Use ironic network for provisioning (bsc#1108398)
  chef/cookbooks/ironic/recipes/server.rb
  chef/cookbooks/ironic/templates/default/ironic.conf.erb
Labels: backport from SOC9

#1914 galera: Use monitoring user for observing wsrep state
  chef/cookbooks/mysql/recipes/ha_galera.rb
Labels: needs backport to SOC7, needs backport to SOC8

#1609 horizon: load monasca from databag
  chef/cookbooks/horizon/libraries/helper.rb
  chef/cookbooks/horizon/recipes/monasca_ui.rb
Labels: bug, needs backport to SOC7

#1930 [4.0] galera bootstrap fixes
  chef/cookbooks/crowbar-openstack/libraries/provider_ssl_setup.rb
  chef/cookbooks/horizon/libraries/helper.rb
  chef/cookbooks/horizon/recipes/monasca_ui.rb
  chef/cookbooks/mysql/recipes/ha_galera.rb
Labels: backport from SOC9

#1912 cinder: remove some deprecated drivers from cinder.conf
  chef/cookbooks/cinder/templates/default/cinder.conf.erb
Labels: wip

#1923 [4.0] database: Prevent deploying mysql-server role to monasca node
  crowbar_framework/app/models/database_service.rb
  crowbar_framework/config/locales/database/en.yml
Labels: needs forward-port to SOC8

#1943 [5.0] Fix SSL (bsc#1114851)
  chef/cookbooks/cinder/recipes/api.rb
  chef/cookbooks/cinder/recipes/common.rb
  chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
  chef/cookbooks/keystone/providers/register.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/keystone/recipes/update_endpoint.rb
  chef/cookbooks/keystone/resources/register.rb
  chef/cookbooks/neutron/recipes/server.rb
  chef/cookbooks/nova/recipes/api.rb
  chef/cookbooks/nova/templates/default/nova.conf.erb
Labels: backport from SOC9

#1906 [5.0] upgrade: reduce keystone downtime
  chef/cookbooks/keystone/recipes/server.rb
  crowbar_framework/lib/openstack/upgrade.rb
Labels: needs forward-port to SOC9, upgrade

#1701 mysql: create .my.cnf in root home directory for mysql cmdline
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/recipes/server.rb
  chef/cookbooks/mysql/templates/default/root-my.cnf.erb
Labels: needs backport to SOC7, needs backport to SOC8

#1946 nova-compute: stop installing qemu-kvm
  chef/cookbooks/nova/recipes/compute.rb
Labels: backport from SOC9

#1950 neutron: scale up api workers on larger core envs
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
Labels: needs backport to SOC8
