Repository crowbar/crowbar-openstack, pull requests merged in 2019-01, with the labels that each got.

#1944 [4.0] Fix SSL (bsc#1114851)
  chef/cookbooks/cinder/recipes/api.rb
  chef/cookbooks/cinder/recipes/common.rb
  chef/cookbooks/horizon/templates/suse/openstack-dashboard.conf.erb
  chef/cookbooks/keystone/providers/register.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/keystone/recipes/update_endpoint.rb
  chef/cookbooks/keystone/resources/register.rb
  chef/cookbooks/neutron/recipes/server.rb
  chef/cookbooks/nova/recipes/api.rb
  chef/cookbooks/nova/templates/default/nova.conf.erb
Labels: backport from SOC9

#1936 database: Prevent deploying mysql-server role to monasca node
  crowbar_framework/app/models/database_service.rb
  crowbar_framework/config/locales/database/en.yml
Labels: forward-port from SOC7, needs backport to SOC8

#1958 [5.0] database: Prevent deploying mysql-server role to monasca node
  crowbar_framework/app/models/database_service.rb
  crowbar_framework/config/locales/database/en.yml
Labels: backport from SOC9

#1947 [5.0] mariadb: Set wsrep_sst_method to mariabackup (bsc#1116686)
  chef/cookbooks/mysql/templates/default/galera.cnf.erb
Labels: needs backport to SOC7, needs forward-port to SOC9

#1964 upgrade: Do not run nova online-db-migrations from chef
  chef/cookbooks/nova/recipes/database.rb
Labels: forward-port from SOC8, upgrade

#1951 upgrade: reduce keystone downtime
  chef/cookbooks/keystone/recipes/server.rb
  crowbar_framework/lib/openstack/upgrade.rb
Labels: forward-port from SOC8, upgrade

#1983 [5.0] database: Fix backport schema migrations actualy safe for backporting
  chef/data_bags/crowbar/migrate/database/200_add_slow_query.rb
  chef/data_bags/crowbar/migrate/database/201_add_tuning_variables.rb
  chef/data_bags/crowbar/migrate/database/202_add_ssl.rb
  chef/data_bags/crowbar/migrate/database/203_add_expire_logs_days.rb
Labels: upgrade

#1981 monasca: Detect failure during monasca-installer run
  chef/cookbooks/monasca/recipes/master.rb
Labels: needs backport to SOC8

#1984 database: Hide SSL options from database UI
  crowbar_framework/app/views/barclamp/database/_edit_attributes.html.haml
Labels: forward-port from SOC7
