Repository crowbar/crowbar-openstack, pull requests merged in 2019-06, with the labels that each got.

#2143 [5.0] nova: Don't retry creating existing flavors
  chef/cookbooks/nova/recipes/flavors.rb
Labels: backport from SOC9

#2149 [5.0] rabbitmq: Fix ACL of SSL key after uid/gid change
  chef/cookbooks/rabbitmq/recipes/ha.rb
Labels: forward-port from SOC7

#2148 rabbitmq: Fix ACL of SSL key after uid/gid change
  chef/cookbooks/rabbitmq/recipes/ha.rb
Labels: forward-port from SOC7

#2151 Upgrade nova
  chef/cookbooks/nova/recipes/database.rb
Labels: upgrade

#2152 monasca: use string keys for attrs in migrations
  chef/data_bags/crowbar/migrate/monasca/302_add_mondb.rb
  chef/data_bags/crowbar/migrate/monasca/303_add_grafanadb.rb
  chef/data_bags/crowbar/migrate/monasca/304_rename_elastic_params.rb
Labels: upgrade

#2150 Configurable timeout for Galera pre-sync
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/data_bags/crowbar/migrate/database/302_add_presync_timeout.rb
  chef/data_bags/crowbar/template-database.json
  chef/data_bags/crowbar/template-database.schema
Labels: needs backport to SOC7, needs backport to SOC8
