Repository crowbar/crowbar-openstack, pull requests merged in 2019-11, with the labels that each got.

#2293 Make sure the input file with ssh key exists
  chef/cookbooks/nova/recipes/compute.rb
Labels: needs backport to SOC8

#2300 [5.0] Make sure the input file with ssh key exists (SOC-10133)
  chef/cookbooks/nova/recipes/compute.rb
Labels: backport from SOC9

#2301 [4.0] Make sure the input file with ssh key exists (SOC-10133)
  chef/cookbooks/nova/recipes/compute.rb
Labels: backport from SOC9

#2298 [4.0 Cloud 7 WSREP fixes
  chef/cookbooks/mysql/recipes/ha_galera.rb
Labels: backport from SOC8

#2308 designate: add support for SSL (SOC-10877)
  chef/cookbooks/designate/attributes/default.rb
  chef/cookbooks/designate/recipes/api.rb
  chef/cookbooks/designate/templates/default/designate.conf.erb
  chef/cookbooks/horizon/recipes/server.rb
  chef/data_bags/crowbar/migrate/designate/302_add_ssl_attributes.rb
  chef/data_bags/crowbar/template-designate.json
  chef/data_bags/crowbar/template-designate.schema
  crowbar_framework/app/helpers/barclamp/designate_helper.rb
  crowbar_framework/app/views/barclamp/designate/_edit_attributes.html.haml
  crowbar_framework/config/locales/designate/en.yml
Labels: needs backport to SOC8

#2307 horizon: install lbaas horizon dashboard (SOC-10883)
  chef/cookbooks/horizon/recipes/server.rb
Labels: needs backport to SOC7, needs backport to SOC8

#2314 [5.0] horizon: install lbaas horizon dashboard (SOC-10883)
  chef/cookbooks/horizon/recipes/server.rb
Labels: backport from SOC9
