Repository crowbar/crowbar-openstack, pull requests merged in 2019-08, with the labels that each got.

#2184 add max_threads_per_process tuneable (SOC-10001)
  chef/cookbooks/nova/recipes/compute.rb
  chef/cookbooks/nova/templates/default/qemu.conf.erb
  chef/data_bags/crowbar/migrate/nova/305_add_max_threads.rb
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
Labels: needs backport to SOC7, needs backport to SOC8

#2185 [5.0] nova: add max_threads_per_process tuneable (SOC-10001)
  chef/cookbooks/nova/recipes/compute.rb
  chef/cookbooks/nova/templates/default/qemu.conf.erb
  chef/data_bags/crowbar/migrate/nova/211_add_max_threads.rb
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
Labels: backport from SOC9, do not merge yet

#2186 SOC-10001: add max_threads_per_process tuneable
  chef/cookbooks/nova/recipes/compute.rb
  chef/cookbooks/nova/templates/default/qemu.conf.erb
  chef/data_bags/crowbar/migrate/nova/126_add_max_threads.rb
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
Labels: backport from SOC8, do not merge yet

#2176 [5.0] designate: Use server node for VIP look ups (SOC-9631)
  chef/cookbooks/designate/recipes/common.rb
Labels: backport from SOC9

#2187 ceilometer: Remove old ceilometer-api vhosts (SOC-9483)
  chef/cookbooks/ceilometer/recipes/server.rb
Labels: upgrade

#2200 memcache: lookup memcached servers port only on local node (SOC-10173)
  chef/cookbooks/barbican/recipes/common.rb
  chef/cookbooks/ceilometer/recipes/common.rb
  chef/cookbooks/cinder/recipes/common.rb
  chef/cookbooks/designate/recipes/common.rb
  chef/cookbooks/ec2-api/recipes/ec2api.rb
  chef/cookbooks/glance/recipes/api.rb
  chef/cookbooks/heat/recipes/server.rb
  chef/cookbooks/horizon/recipes/server.rb
  chef/cookbooks/ironic/recipes/server.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/magnum/recipes/common.rb
  chef/cookbooks/manila/recipes/common.rb
  chef/cookbooks/memcached/libraries/helpers.rb
  chef/cookbooks/monasca/recipes/monasca_api.rb
  chef/cookbooks/monasca/recipes/monasca_log_api.rb
  chef/cookbooks/neutron/recipes/common_config.rb
  chef/cookbooks/nova/recipes/config.rb
  chef/cookbooks/sahara/recipes/common.rb
  chef/cookbooks/swift/recipes/proxy.rb
  chef/cookbooks/swift/recipes/storage.rb
Labels: needs backport to SOC8

#2201 [5.0] horizon: Install designate plugin when configured (SOC-9695)
  chef/cookbooks/aodh/recipes/aodh.rb
  chef/cookbooks/barbican/recipes/common.rb
  chef/cookbooks/ceilometer/recipes/common.rb
  chef/cookbooks/cinder/recipes/common.rb
  chef/cookbooks/designate/recipes/common.rb
  chef/cookbooks/ec2-api/recipes/ec2api.rb
  chef/cookbooks/glance/recipes/api.rb
  chef/cookbooks/glance/recipes/registry.rb
  chef/cookbooks/heat/recipes/server.rb
  chef/cookbooks/horizon/recipes/server.rb
  chef/cookbooks/ironic/recipes/server.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/magnum/recipes/common.rb
  chef/cookbooks/manila/recipes/common.rb
  chef/cookbooks/memcached/libraries/helpers.rb
  chef/cookbooks/neutron/recipes/common_config.rb
  chef/cookbooks/nova/recipes/config.rb
  chef/cookbooks/sahara/recipes/common.rb
  chef/cookbooks/swift/recipes/proxy.rb
  chef/cookbooks/swift/recipes/storage.rb
  chef/cookbooks/trove/recipes/api.rb
  crowbar_framework/app/models/designate_service.rb
Labels: backport from SOC9

#2190 [5.0] Add tempest filters based on services (SOC-9799)
  chef/cookbooks/tempest/files/default/run_filters/aodh.txt
  chef/cookbooks/tempest/files/default/run_filters/barbican.txt
  chef/cookbooks/tempest/files/default/run_filters/ceilometer.txt
  chef/cookbooks/tempest/files/default/run_filters/cinder.txt
  chef/cookbooks/tempest/files/default/run_filters/fwaas.txt
  chef/cookbooks/tempest/files/default/run_filters/glance.txt
  chef/cookbooks/tempest/files/default/run_filters/heat.txt
  chef/cookbooks/tempest/files/default/run_filters/keystone.txt
  chef/cookbooks/tempest/files/default/run_filters/lbaas.txt
  chef/cookbooks/tempest/files/default/run_filters/magnum.txt
  chef/cookbooks/tempest/files/default/run_filters/manila.txt
  chef/cookbooks/tempest/files/default/run_filters/neutron.txt
  chef/cookbooks/tempest/files/default/run_filters/nova.txt
  chef/cookbooks/tempest/files/default/run_filters/smoke.txt
  chef/cookbooks/tempest/files/default/run_filters/swift.txt
  chef/cookbooks/tempest/files/default/run_filters/trove.txt
  chef/cookbooks/tempest/files/default/tests2skip.py
  chef/cookbooks/tempest/recipes/config.rb
Labels: backport from SOC9, do not merge yet

#2183 [5.0] horizon: fix Grafana in HA clouds (bsc#1116846)
  chef/cookbooks/horizon/recipes/monasca_ui.rb
Labels: backport from SOC9
