Repository crowbar/crowbar-openstack, pull requests merged in 2019-05, with the labels that each got.

#2116 neutron: use crm_resource restart for restarting neutron-l3-ha-service
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: needs backport to SOC7, needs backport to SOC8, needs forward-port to SOC9

#2036 [5.0] Add Option to use L3 HA with Keepalived for Neutron router failover
  chef/cookbooks/ceilometer/recipes/central_ha.rb
  chef/cookbooks/neutron/attributes/default.rb
  chef/cookbooks/neutron/recipes/common_agent.rb
  chef/cookbooks/neutron/recipes/common_config.rb
  chef/cookbooks/neutron/recipes/network_agents.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
  chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
  chef/cookbooks/nova/recipes/compute_ha.rb
  chef/data_bags/crowbar/migrate/neutron/213_add_use_l3_ha.rb
  chef/data_bags/crowbar/template-neutron.json
  chef/data_bags/crowbar/template-neutron.schema
  crowbar_framework/app/models/neutron_service.rb
Labels: backport from SOC9

#2114 database: Raise and align promote/demote timeouts (bsc#1131791)
  chef/data_bags/crowbar/template-database.json
Labels: needs backport to SOC7, needs backport to SOC8

#2125 [5.0] database: Raise and align promote/demote timeouts (bsc#1131791)
  chef/data_bags/crowbar/template-database.json
Labels: backport from SOC9

#2127 database: Make wsrep_provider_options configurable (fate#327745)
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/templates/default/galera.cnf.erb
  chef/data_bags/crowbar/migrate/database/301_make_wsrep_provider_options_configurable.rb
  chef/data_bags/crowbar/template-database.json
  chef/data_bags/crowbar/template-database.schema
Labels: needs backport to SOC7, needs backport to SOC8

#2119 [5.0] Fix neutron-ha-tool restart on configuration changes
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: backport from SOC9

#2126 [4.0] database: Raise and align promote/demote timeouts (bsc#1131791)
  chef/data_bags/crowbar/template-database.json
Labels: backport from SOC9

#2129 [5.0] database: Make wsrep_provider_options configurable (fate#327745)
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/templates/default/galera.cnf.erb
  chef/data_bags/crowbar/migrate/database/210_make_wsrep_provider_options_configurable.rb
  chef/data_bags/crowbar/template-database.json
  chef/data_bags/crowbar/template-database.schema
Labels: backport from SOC9

#2130 [4.0] database: Make wsrep_provider_options configurable (fate#327745)
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/templates/default/galera.cnf.erb
  chef/data_bags/crowbar/migrate/database/111_make_wsrep_provider_options_configurable.rb
  chef/data_bags/crowbar/template-database.json
  chef/data_bags/crowbar/template-database.schema
Labels: backport from SOC9

#2131 nova: Show stdout/stderr when "openstack flavor list" fails
  chef/cookbooks/nova/recipes/flavors.rb
Labels: needs backport to SOC8

#2134 nova: Show stdout/stderr when "openstack flavor list" fails
  chef/cookbooks/nova/recipes/flavors.rb
Labels: backport from SOC9

#2137 neutron: Don't restart l3-ha on .openrc change + timeout extension
  chef/cookbooks/neutron/attributes/default.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: needs backport to SOC7, needs backport to SOC8

#2120 [4.0] Fix neutron-ha-tool restart on configuration changes
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: backport from SOC8, backport from SOC9

#2140 [5.0] neutron: Don't restart l3-ha on .openrc change + timeout extension
  chef/cookbooks/neutron/attributes/default.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: backport from SOC9
