Repository crowbar/crowbar-openstack, pull requests merged in 2019-10, with the labels that each got.

#2272 monasca: Fix restore condition (SOC-9772)
  chef/cookbooks/monasca/recipes/monasca_api.rb
Labels: upgrade

#2155 [5.0] Configurable timeout for Galera pre-sync
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/data_bags/crowbar/migrate/database/211_add_presync_timeout.rb
  chef/data_bags/crowbar/template-database.json
  chef/data_bags/crowbar/template-database.schema
Labels: backport from SOC9

#2290 [4.0] Do not use obsoleted --endpoint-type option with CLI
  chef/cookbooks/neutron/recipes/post_install_conf.rb
Labels: needs forward-port to SOC8

#2289 [4.0] Configurable timeout for Galera pre-sync
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/data_bags/crowbar/migrate/database/112_add_presync_timeout.rb
  chef/data_bags/crowbar/template-database.json
  chef/data_bags/crowbar/template-database.schema
Labels: backport from SOC9

#2285 mysql: stop service for mysql_install_db (SOC-10717)
  chef/cookbooks/mysql/recipes/ha_galera.rb
Labels: needs backport to SOC8

#2288 mysql: fix WSREP sync race (SOC-10717)
  chef/cookbooks/mysql/recipes/ha_galera.rb
Labels: needs backport to SOC8

#2291 [5.0] Set OS_ENDPOINT_TYPE to be used with CLI
  chef/cookbooks/neutron/recipes/post_install_conf.rb
Labels: forward-port from SOC7

#2295 [5.0] C8 wsrep fixes
  chef/cookbooks/mysql/recipes/ha_galera.rb
Labels: backport from SOC9

#2204 Octavia: Follow up patch addressing comments from last PR (SOC-9894)
  chef/cookbooks/octavia/README.rdoc
  chef/cookbooks/octavia/attributes/default.rb
  chef/cookbooks/octavia/definitions/octavia_conf.rb
  chef/cookbooks/octavia/definitions/octavia_service.rb
  chef/cookbooks/octavia/libraries/helpers.rb
  chef/cookbooks/octavia/metadata.json
  chef/cookbooks/octavia/metadata.rb
  chef/cookbooks/octavia/recipes/api.rb
  chef/cookbooks/octavia/recipes/api_ha.rb
  chef/cookbooks/octavia/recipes/common.rb
  chef/cookbooks/octavia/recipes/database.rb
  chef/cookbooks/octavia/recipes/health_manager.rb
  chef/cookbooks/octavia/recipes/housekeeping.rb
  chef/cookbooks/octavia/recipes/https.rb
  chef/cookbooks/octavia/recipes/keystone.rb
  chef/cookbooks/octavia/recipes/nova.rb
  chef/cookbooks/octavia/recipes/role_octavia_api.rb
  chef/cookbooks/octavia/recipes/role_octavia_backend.rb
  chef/cookbooks/octavia/recipes/worker.rb
  chef/cookbooks/octavia/templates/default/100-octavia.conf.erb
  chef/cookbooks/octavia/templates/default/110-api.conf.erb
  chef/cookbooks/octavia/templates/default/110-health-manager.conf.erb
  chef/cookbooks/octavia/templates/default/110-housekeeping.conf.erb
  chef/cookbooks/octavia/templates/default/110-worker.conf.erb
  chef/data_bags/crowbar/template-octavia.json
  chef/data_bags/crowbar/template-octavia.schema
  crowbar_framework/app/models/octavia_service.rb
  crowbar_framework/app/views/barclamp/octavia/_edit_attributes.html.haml
Labels: Octavia
