Repository crowbar/crowbar-openstack, pull requests merged in 2019-09, with the labels that each got.

#2222 nova: Don't put nova-compute roles on monasca node (SOC-10373)
  crowbar_framework/app/models/nova_service.rb
Labels: upgrade

#2223 [5.0] nova: Don't put nova-compute roles on monasca node (SOC-1…
  crowbar_framework/app/models/nova_service.rb
Labels: backport from SOC9, upgrade

#2193 neutron-lbaas: remove loadbalancer/pool limit
  chef/cookbooks/neutron/templates/default/neutron_lbaas.conf.erb
Labels: needs backport to SOC7, needs backport to SOC8

#2210 nova: raise neutron client timeout to 5 minutes
  chef/cookbooks/nova/attributes/default.rb
  chef/data_bags/crowbar/template-nova.json
Labels: needs backport to SOC8

#2233 [5.0] ECP backports
  chef/cookbooks/neutron/templates/default/neutron_lbaas.conf.erb
  chef/cookbooks/nova/attributes/default.rb
  chef/data_bags/crowbar/template-nova.json
Labels: backport from SOC9

#2243 Add tempest filter for designate (SOC-10288)
  chef/cookbooks/tempest/files/default/run_filters/designate.txt
Labels: needs backport to SOC8

#2252 nova: set default attribute for max_threads_per_process
  chef/cookbooks/nova/attributes/default.rb
Labels: needs backport to SOC7, needs backport to SOC8

#2177 Upgrade: restore Monasca DB [SOC-9772]
  chef/cookbooks/horizon/recipes/monasca_ui.rb
  chef/cookbooks/monasca/recipes/monasca_api.rb
  crowbar_framework/lib/openstack/upgrade.rb
Labels: upgrade

#2259 designate: Fix the keys syntax error on migrations (SOC-10660)
  chef/data_bags/crowbar/migrate/designate/301_add_resources.rb
Labels: needs backport to SOC8

#2262 glance: don't reuse sync mark names (SOC-10348)
  chef/cookbooks/glance/recipes/api.rb
Labels: needs backport to SOC8

#2248 rabbitmq: fix migrations (SOC-10623)
  chef/data_bags/crowbar/migrate/cinder/205_add_resource_limits.rb
  chef/data_bags/crowbar/migrate/database/205_add_resource_limits.rb
  chef/data_bags/crowbar/migrate/database/206_add_bootstrap_timeout.rb
  chef/data_bags/crowbar/migrate/database/302_add_presync_timeout.rb
  chef/data_bags/crowbar/migrate/horizon/203_add_resource_limits.rb
  chef/data_bags/crowbar/migrate/nova/207_add_resource_limits.rb
  chef/data_bags/crowbar/migrate/rabbitmq/200_add_resource_limits.rb
  chef/data_bags/crowbar/migrate/rabbitmq/201_heartbeat_timeout.rb
  chef/data_bags/crowbar/migrate/rabbitmq/202_add_mnesia_dump_log.rb
  chef/data_bags/crowbar/migrate/rabbitmq/203_add_performance_config.rb
  chef/data_bags/crowbar/migrate/rabbitmq/204_add_extra_users.rb
Labels: needs backport to SOC8

#2238 helper: move config_for_role_exists from horizon to crowbar-openstack (SOC-10191)
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
  chef/cookbooks/horizon/libraries/helper.rb
  chef/cookbooks/horizon/recipes/server.rb
  chef/cookbooks/tempest/recipes/install.rb
Labels: needs backport to SOC8

#2255 tempest: don't rely on service catalogue (SOC-10633)
  chef/cookbooks/tempest/recipes/config.rb
Labels: needs backport to SOC7, needs backport to SOC8

#2265 [4.0] tempest: don't rely on service catalogue (SOC-10633)
  chef/cookbooks/tempest/recipes/config.rb
Labels: backport from SOC8

#2264 [5.0] tempest: don't rely on service catalogue (SOC-10633)
  chef/cookbooks/tempest/recipes/config.rb
Labels: backport from SOC9

#2263 [5.0] glance: don't reuse sync mark names (SOC-10348)
  chef/cookbooks/glance/recipes/registry.rb
Labels: backport from SOC9

#2256 [5.0] nova: set default attribute for max_threads_per_process
  chef/cookbooks/nova/attributes/default.rb
Labels: backport from SOC9

#2257 [4.0] nova: set default attribute for max_threads_per_process
  chef/cookbooks/nova/attributes/default.rb
Labels: backport from SOC8, backport from SOC9

#2274 [5.0] helper:move config_for_role_exists from horizon to crowbar-openstack(SOC-10191)
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
  chef/cookbooks/horizon/recipes/server.rb
Labels: backport from SOC9
