Repository crowbar/crowbar-openstack, pull requests merged in 2019-03, with the labels that each got.

#2049 [4.0] rabbit: fix mirroring regex
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
Labels: backport from SOC9

#2047 rabbit: fix mirroring regex
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
Labels: needs backport to SOC7, needs backport to SOC8

#2048 [5.0] rabbit: fix mirroring regex
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
Labels: backport from SOC9

#2023 mysql: improve galera HA setup (bsc#1122875)
  chef/cookbooks/mysql/recipes/ha_galera.rb
Labels: needs backport to SOC7, needs backport to SOC8

#2073 memcache: Use first array element as fallback (SCRD-8255)
  chef/cookbooks/memcached/libraries/helpers.rb
Labels: needs backport to SOC8

#2066 [5.0] db: Raise default connection limit to 2048
  chef/data_bags/crowbar/template-database.json
Labels: backport from SOC9

#2077 [5.0] memcache: Use first array element as fallback (SCRD-8255)
  chef/cookbooks/memcached/libraries/helpers.rb
Labels: backport from SOC9

#2069 neutron: properly define region (bsc#1128753)
  chef/cookbooks/neutron/templates/default/neutron_lbaas.conf.erb
Labels: needs backport to SOC8
