Repository crowbar/crowbar-openstack, pull requests merged in 2019-02, with the labels that each got.

#1962 nova: cleanup ceph key handling
  chef/cookbooks/nova/recipes/ceph.rb
Labels: needs backport to SOC8

#1952 [5.0] neutron: scale up api workers on larger core envs
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
Labels: backport from SOC9

#1949 cinder: Set cinder pool to exclusive by default when using embedded ceph
  chef/cookbooks/cinder/templates/default/cinder.conf.erb
Labels: needs backport to SOC8

#2021 mysql: Do not set a custom logfile for mysqld (bsc#1112767)
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/templates/default/logging.cnf.erb
Labels: needs backport to SOC7, needs backport to SOC8

#2022 [5.0] mysql: Do not set a custom logfile for mysqld (bsc#1112767)
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/templates/default/logging.cnf.erb
Labels: backport from SOC9

#2020 [4.0] mysql: create .my.cnf in root home directory for mysql cmdline
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/recipes/server.rb
  chef/cookbooks/mysql/templates/default/root-my.cnf.erb
Labels: backport from SOC9

#2024 [4.0] mysql: Do not set a custom logfile for mysqld (bsc#1112767)
  chef/cookbooks/mysql/recipes/ha_galera.rb
  chef/cookbooks/mysql/templates/default/logging.cnf.erb
Labels: backport from SOC8

#2025 [4.0] ceilometer: Use pacemaker to handle expirer cron link (bsc#1113107)
  chef/cookbooks/ceilometer/attributes/default.rb
  chef/cookbooks/ceilometer/recipes/server_ha.rb
Labels: needs forward-port to SOC8

#2005 neutron: Added option to use L3 HA with Keepalived
  chef/cookbooks/ceilometer/recipes/central_ha.rb
  chef/cookbooks/neutron/attributes/default.rb
  chef/cookbooks/neutron/recipes/common_agent.rb
  chef/cookbooks/neutron/recipes/common_config.rb
  chef/cookbooks/neutron/recipes/network_agents.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
  chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
  chef/cookbooks/nova/recipes/compute_ha.rb
  chef/data_bags/crowbar/migrate/neutron/304_add_use_l3_ha.rb
  chef/data_bags/crowbar/template-neutron.json
  chef/data_bags/crowbar/template-neutron.schema
  crowbar_framework/app/models/neutron_service.rb
Labels: needs backport to SOC7, needs backport to SOC8

#2028 [5.0] ceilometer: Use pacemaker to handle expirer cron link (bsc#1113107)
  chef/cookbooks/ceilometer/attributes/default.rb
  chef/cookbooks/ceilometer/recipes/server_ha.rb
Labels: forward-port from SOC7

#2030 mysql: Enable "explain" in the slow query log file
  chef/cookbooks/mysql/templates/default/logging.cnf.erb
Labels: needs backport to SOC8

#2031 [5.0] osprofiler support
  chef/cookbooks/cinder/recipes/common.rb
  chef/cookbooks/cinder/templates/default/cinder.conf.erb
  chef/cookbooks/glance/recipes/api.rb
  chef/cookbooks/glance/recipes/cache.rb
  chef/cookbooks/glance/recipes/scrubber.rb
  chef/cookbooks/glance/templates/default/glance-api.conf.erb
  chef/cookbooks/glance/templates/default/glance-cache.conf.erb
  chef/cookbooks/glance/templates/default/glance-scrubber.conf.erb
  chef/cookbooks/keystone/libraries/helpers.rb
  chef/cookbooks/keystone/recipes/server.rb
  chef/cookbooks/keystone/templates/default/keystone.conf.erb
  chef/cookbooks/neutron/recipes/common_config.rb
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
  chef/cookbooks/nova/recipes/config.rb
  chef/cookbooks/nova/templates/default/nova-placement.conf.erb
  chef/cookbooks/nova/templates/default/nova.conf.erb
  chef/data_bags/crowbar/migrate/keystone/206_add_osprofiler.rb
  chef/data_bags/crowbar/migrate/keystone/207_add_osprofiler_connection_string.rb
  chef/data_bags/crowbar/template-keystone.json
  chef/data_bags/crowbar/template-keystone.schema
  crowbar_framework/app/models/keystone_service.rb
Labels: backport from SOC9
