Repository crowbar/crowbar-openstack, pull requests merged in 2019-07, with the labels that each got.

#2141 [4.0] neutron: Don't restart l3-ha on .openrc change + timeout extension
  chef/cookbooks/neutron/attributes/default.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: backport from SOC9

#2159 monasca: move Grafana DB creation
  chef/cookbooks/horizon/recipes/monasca_ui.rb
  chef/cookbooks/monasca/recipes/database.rb
Labels: upgrade

#2153 case-insensitive role name lookup (SOC-9339)
  chef/cookbooks/keystone/providers/register.rb
Labels: upgrade

#2163 [5.0] cinder: Set cinder pool to exclusive by default when using embedded ceph
  chef/cookbooks/cinder/templates/default/cinder.conf.erb
Labels: backport from SOC9

#2165 Improve Mnesia IO performances
  chef/data_bags/crowbar/template-rabbitmq.json
Labels: backport from SOC9

#2160 [5.0] swift: Sync HA nodes (SOC-9683)
  chef/cookbooks/swift/recipes/proxy.rb
Labels: backport from SOC9

#2174 Cleanup clone_stateless_services leftovers (SOC-9842)
  crowbar_framework/lib/openstack/upgrade.rb
Labels: upgrade

#2169 Fix barbican SSL support (SOC-9298)
  chef/cookbooks/barbican/recipes/ha.rb
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
Labels: needs backport to SOC7, needs backport to SOC8

#2173 Tempest fixes for nova and magnum (SOC-9298)
  chef/cookbooks/magnum/templates/default/magnum.conf.erb
  chef/cookbooks/tempest/recipes/config.rb
  chef/cookbooks/tempest/templates/default/tempest.conf.erb
  chef/data_bags/crowbar/template-tempest.json
Labels: needs backport to SOC7, needs backport to SOC8

#2178 upgrade: Fix HA detection for keystone db_sync (SOC-9981)
  crowbar_framework/lib/openstack/upgrade.rb
Labels: upgrade
