Repository crowbar/crowbar-openstack, pull requests merged in 2019-12, with the labels that each got.

#2320 octavia: configuration fixes (SOC-10989,SOC-10990)
  chef/cookbooks/octavia/definitions/octavia_conf.rb
  chef/cookbooks/octavia/libraries/helpers.rb
  chef/cookbooks/octavia/templates/default/100-octavia.conf.erb
  chef/cookbooks/octavia/templates/default/110-api.conf.erb
Labels: do not merge yet

#2323 keystone: Add OS_INTERFACE env var to .openrc (SOC-11006)
  chef/cookbooks/keystone/templates/default/openrc.erb
Labels: upgrade

#2324 [5.0] keystone: Add OS_INTERFACE env var to .openrc (SOC-11006)
  chef/cookbooks/keystone/templates/default/openrc.erb
Labels: backport from SOC9, upgrade

#2325 neutron: Revert remove .openrc creation from neutron cookbooks (SOC-10378)
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: upgrade

#2327 tempest: Update default image on schema (SOC-11023)
  chef/data_bags/crowbar/migrate/tempest/302_update_tempest_image.rb
  chef/data_bags/crowbar/template-tempest.json
Labels: needs backport to SOC8

#2336 [5.0] Do not read data from barclamp that has not been saved (SOC-11028)
  chef/cookbooks/neutron/recipes/post_install_conf.rb
  chef/cookbooks/nova/libraries/availability_zone.rb
  chef/cookbooks/nova/recipes/flavors.rb
Labels: backport from SOC9

#2329 octavia: Install amphora image always (SOC-11024)
  chef/cookbooks/octavia/libraries/helpers.rb
  chef/cookbooks/octavia/recipes/nova.rb
Labels: Octavia
