Repository crowbar/crowbar-openstack, pull requests merged in 2019-04, with the labels that each got.

#2084 monasca: Set hostname for monasca-agent as FQDN (SCRD-8705)
  chef/cookbooks/monasca/recipes/agent.rb
Labels: needs backport to SOC8

#2087 [5.0] monasca: Set hostname for monasca-agent as FQDN (SCRD-8705)
  chef/cookbooks/monasca/recipes/agent.rb
Labels: backport from SOC9

#2074 [5.0] ceilometer: Install package which contains cron file (bsc#1130414)
  chef/cookbooks/ceilometer/recipes/server_ha.rb
Labels: needs backport to SOC7

#2080 Improve Mnesia IO performances
  chef/data_bags/crowbar/template-rabbitmq.json
Labels: needs backport to SOC8

#2079 [5.0] Neutron LBaaS fixes
  chef/cookbooks/neutron/templates/default/neutron_lbaas.conf.erb
Labels: backport from SOC9, needs backport to SOC7

#2091 [4.0] ironic: Fix regression in helper
  chef/cookbooks/ironic/libraries/helpers.rb
Labels: backport from SOC8

#2043 [4.0] neutron: Added option to use L3 HA with Keepalived
  chef/cookbooks/neutron/attributes/default.rb
  chef/cookbooks/neutron/recipes/common_agent.rb
  chef/cookbooks/neutron/recipes/common_config.rb
  chef/cookbooks/neutron/recipes/network_agents.rb
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
  chef/cookbooks/neutron/templates/default/l3_agent.ini.erb
  chef/cookbooks/neutron/templates/default/neutron.conf.erb
  chef/data_bags/crowbar/migrate/neutron/123_add_use_l3_ha.rb
  chef/data_bags/crowbar/template-neutron.json
  chef/data_bags/crowbar/template-neutron.schema
  crowbar_framework/app/models/neutron_service.rb
Labels: backport from SOC8, backport from SOC9

#2112 neutron: restart neutron-ha-tool when the config file changes
  chef/cookbooks/neutron/recipes/network_agents_ha.rb
Labels: needs backport to SOC7, needs backport to SOC8
