Repository crowbar/crowbar-openstack, pull requests merged in 2020-04, with the labels that each got.

#2389 [5.0] monasca: disable postgres backend monitoring by default (SOC-11190)
  chef/cookbooks/barbican/recipes/monitor_monasca.rb
  chef/cookbooks/cinder/recipes/monitor_monasca.rb
  chef/cookbooks/glance/recipes/monitor_monasca.rb
  chef/cookbooks/heat/recipes/monitor_monasca.rb
  chef/cookbooks/keystone/recipes/monitor_monasca.rb
  chef/cookbooks/magnum/recipes/monitor_monasca.rb
  chef/cookbooks/manila/recipes/monitor_monasca.rb
  chef/cookbooks/monasca/providers/agent_plugin_postgres.rb
  chef/cookbooks/monasca/resources/agent_plugin_postgres.rb
  chef/cookbooks/neutron/recipes/monitor_monasca.rb
  chef/cookbooks/nova/recipes/monitor_monasca.rb
  chef/cookbooks/sahara/recipes/monitor_monasca.rb
Labels: backport from SOC9

#2394 [5.0] tempest: disable block migration when using RBD (SOC-11176)
  chef/cookbooks/tempest/recipes/config.rb
  chef/cookbooks/tempest/templates/default/tempest.conf.erb
Labels: backport from SOC9

#2396 tempest: retry openstack commands (SOC-11238)
  chef/cookbooks/tempest/recipes/config.rb
Labels: needs backport to SOC8

#2397 [5.0] tempest: retry openstack commands (SOC-11238)
  chef/cookbooks/tempest/recipes/config.rb
Labels: backport from SOC9

#2398 tempest: retry openstack commands (SOC-11238)
  chef/cookbooks/tempest/recipes/config.rb
Labels: backport from SOC9

#2400 run keystone_register on cluster founder only when HA (SOC-11248)
  chef/cookbooks/barbican/recipes/api.rb
  chef/cookbooks/ceilometer/recipes/server.rb
  chef/cookbooks/cinder/recipes/api.rb
  chef/cookbooks/designate/recipes/api.rb
  chef/cookbooks/glance/recipes/api.rb
  chef/cookbooks/glance/recipes/common.rb
  chef/cookbooks/magnum/recipes/api.rb
  chef/cookbooks/manila/recipes/api.rb
  chef/cookbooks/neutron/recipes/api_register.rb
  chef/cookbooks/octavia/recipes/keystone.rb
  chef/cookbooks/sahara/recipes/api.rb
  chef/cookbooks/swift/recipes/proxy.rb
  chef/cookbooks/watcher/recipes/common.rb
  chef/cookbooks/watcher/recipes/server.rb
Labels: needs backport to SOC7, needs backport to SOC8

#2403 [4.0] run keystone_register on cluster founder only when HA (SOC-11248,SOC-11243)
  chef/cookbooks/barbican/recipes/api.rb
  chef/cookbooks/ceilometer/recipes/server.rb
  chef/cookbooks/cinder/recipes/api.rb
  chef/cookbooks/glance/recipes/api.rb
  chef/cookbooks/glance/recipes/common.rb
  chef/cookbooks/magnum/recipes/api.rb
  chef/cookbooks/manila/recipes/api.rb
  chef/cookbooks/neutron/recipes/api_register.rb
  chef/cookbooks/nova/recipes/api.rb
  chef/cookbooks/nova/recipes/placement_api.rb
  chef/cookbooks/sahara/recipes/api.rb
  chef/cookbooks/swift/recipes/proxy.rb
Labels: backport from SOC9

#2402 [5.0] run keystone_register on cluster founder only when HA (SOC-11248,SOC-11243)
  chef/cookbooks/barbican/recipes/api.rb
  chef/cookbooks/ceilometer/recipes/server.rb
  chef/cookbooks/cinder/recipes/api.rb
  chef/cookbooks/designate/recipes/api.rb
  chef/cookbooks/glance/recipes/api.rb
  chef/cookbooks/glance/recipes/common.rb
  chef/cookbooks/magnum/recipes/api.rb
  chef/cookbooks/manila/recipes/api.rb
  chef/cookbooks/neutron/recipes/api_register.rb
  chef/cookbooks/nova/recipes/api.rb
  chef/cookbooks/nova/recipes/placement_api.rb
  chef/cookbooks/sahara/recipes/api.rb
  chef/cookbooks/swift/recipes/proxy.rb
Labels: backport from SOC9
