Repository crowbar/crowbar-openstack, pull requests merged in 2020-01, with the labels that each got.

#2337 Install openstack client for neutron recipes
  chef/cookbooks/neutron/recipes/post_install_conf.rb
Labels: needs forward-port to SOC8

#2338 [5.0] Install openstack client for neutron recipes (SOC-11039)
  chef/cookbooks/neutron/recipes/post_install_conf.rb
Labels: backport from SOC9

#2343 tempest: tempest run filters as templates (SOC-11052)
  chef/cookbooks/tempest/files/default/run_filters/lbaas.txt
  chef/cookbooks/tempest/recipes/config.rb
  chef/cookbooks/tempest/templates/default/run_filters/barbican.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/cinder.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/designate.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/fwaas.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/glance.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/heat.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/keystone.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/lbaas-octavia.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/lbaas.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/magnum.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/manila.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/neutron.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/nova.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/octavia.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/smoke.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/swift.txt.erb
Labels: needs backport to SOC7, needs backport to SOC8

#2345 [5.0] tempest: tempest run filters as templates (SOC-11052)
  chef/cookbooks/tempest/recipes/config.rb
  chef/cookbooks/tempest/templates/default/run_filters/aodh.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/barbican.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/ceilometer.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/cinder.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/designate.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/fwaas.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/glance.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/heat.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/keystone.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/lbaas.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/magnum.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/manila.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/neutron.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/nova.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/smoke.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/swift.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/trove.txt.erb
Labels: backport from SOC9

#2349 rabbitmq: sync startup definitions.json with recipe (SOC-11077)
  chef/cookbooks/rabbitmq/libraries/crowbar.rb
  chef/cookbooks/rabbitmq/recipes/default.rb
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/cookbooks/rabbitmq/templates/default/definitions.json.erb
Labels: needs backport to SOC7, needs backport to SOC8

#2351 [4.0] rabbitmq: sync startup definitions.json with recipe (SOC-11077)
  chef/cookbooks/rabbitmq/libraries/crowbar.rb
  chef/cookbooks/rabbitmq/recipes/default.rb
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/cookbooks/rabbitmq/templates/default/definitions.json.erb
Labels: backport from SOC9

#2352 ec2-api: run keystone_register on cluster founder only (SOC-11079)
  chef/cookbooks/ec2-api/recipes/ec2api.rb
Labels: needs backport to SOC8
