Repository crowbar/crowbar-openstack, pull requests merged in 2020-05, with the labels that each got.

#2412 trove: fix rabbitmq connection URL (SOC-11286)
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
Labels: needs backport to SOC7, needs backport to SOC8

#2413 rabbitmq: sync startup definitions.json with recipe (SOC-11077,SOC-11274)
  chef/cookbooks/rabbitmq/libraries/crowbar.rb
  chef/cookbooks/rabbitmq/recipes/default.rb
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/cookbooks/rabbitmq/templates/default/definitions.json.erb
Labels: needs backport to SOC8

#2414 [5.0] trove: fix rabbitmq connection URL (SOC-11286)
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
Labels: backport from SOC9

#2415 [4.0] trove: fix rabbitmq connection URL (SOC-11286)
  chef/cookbooks/crowbar-openstack/libraries/helpers.rb
Labels: backport from SOC8

#2410 [5.0] rabbitmq: sync startup definitions.json with recipe (SOC-11077,SOC-11274)
  chef/cookbooks/rabbitmq/libraries/crowbar.rb
  chef/cookbooks/rabbitmq/recipes/default.rb
  chef/cookbooks/rabbitmq/recipes/rabbit.rb
  chef/cookbooks/rabbitmq/templates/default/definitions.json.erb
Labels: backport from SOC9

#2419 [5.0] nova: only create nonexistent cell1
  chef/cookbooks/nova/recipes/database.rb
Labels: backport from SOC9
