Repository crowbar/crowbar-openstack, pull requests merged in 2020-03, with the labels that each got.

#2361 [5.0] SES integration and (a bit of) Ceph cleanup
  chef/cookbooks/cinder/metadata.rb
  chef/cookbooks/cinder/recipes/ceph.rb
  chef/cookbooks/glance/metadata.rb
  chef/cookbooks/glance/recipes/ceph.rb
  chef/cookbooks/nova/attributes/default.rb
  chef/cookbooks/nova/metadata.rb
  chef/cookbooks/nova/recipes/ceph.rb
  chef/cookbooks/nova/recipes/ceph_secrets.rb
  chef/cookbooks/nova/recipes/compute.rb
  chef/cookbooks/nova/recipes/config.rb
  chef/data_bags/crowbar/migrate/cinder/208_disable_default_rbd_use_crowbar.rb
  chef/data_bags/crowbar/migrate/cinder/209_add_use_ses.rb
  chef/data_bags/crowbar/migrate/glance/203_add_use_ses.rb
  chef/data_bags/crowbar/migrate/nova/212_remove_rbd.rb
  chef/data_bags/crowbar/template-cinder.json
  chef/data_bags/crowbar/template-cinder.schema
  chef/data_bags/crowbar/template-glance.json
  chef/data_bags/crowbar/template-glance.schema
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
  crowbar_framework/app/models/cinder_service.rb
  crowbar_framework/app/models/glance_service.rb
  crowbar_framework/app/views/barclamp/cinder/_edit_attributes.html.haml
  crowbar_framework/app/views/barclamp/glance/_edit_attributes.html.haml
  crowbar_framework/config/locales/cinder/en.yml
  crowbar_framework/config/locales/glance/en.yml
Labels: backport from SOC9

#2372 [5.0] heat: Simplify domain registration code + timeout increase (SOC-11103)
  chef/cookbooks/heat/recipes/server.rb
Labels: backport from SOC9

#2367 [5.0] keystone: Register SES RadosGW endpoints (SOC-11120)
  chef/cookbooks/keystone/metadata.rb
  chef/cookbooks/keystone/recipes/role_keystone_server.rb
  chef/cookbooks/keystone/recipes/ses.rb
  chef/cookbooks/swift/recipes/proxy.rb
Labels: backport from SOC9

#2364 [5.0] nova: Enable ephemeral volumes on SES (SOC-11119)
  chef/cookbooks/nova/recipes/config.rb
  chef/cookbooks/nova/templates/default/nova.conf.erb
  chef/data_bags/crowbar/migrate/nova/212_add_use_rbd_ephemeral.rb
  chef/data_bags/crowbar/template-nova.json
  chef/data_bags/crowbar/template-nova.schema
  crowbar_framework/app/models/nova_service.rb
  crowbar_framework/app/views/barclamp/nova/_edit_attributes.html.haml
  crowbar_framework/config/locales/nova/en.yml
Labels: backport from SOC9

#2374 magnum: Add SSL support (SOC-9849)
  chef/cookbooks/magnum/attributes/default.rb
  chef/cookbooks/magnum/recipes/common.rb
  chef/cookbooks/magnum/templates/default/magnum.conf.erb
  chef/data_bags/crowbar/migrate/magnum/301_add_ssl_attributes.rb
  chef/data_bags/crowbar/template-magnum.json
  chef/data_bags/crowbar/template-magnum.schema
  crowbar_framework/app/helpers/barclamp/magnum_helper.rb
  crowbar_framework/app/views/barclamp/magnum/_edit_attributes.html.haml
  crowbar_framework/config/locales/magnum/en.yml
Labels: needs backport to SOC8

#2354 [4.0] ec2-api: run keystone_register on cluster founder only (SOC-11079)
  chef/cookbooks/ec2-api/recipes/ec2api.rb
Labels: backport from SOC8

#2379 nova: Populate cinder SES settings early (SOC-11179)
  chef/cookbooks/nova/recipes/config.rb
Labels: needs backport to SOC8

#2382 tempest: update blacklisted tempest test cases (SOC-9801,SOC-11174,SOC-11187)
  chef/cookbooks/tempest/templates/default/run_filters/cinder.txt.erb
  chef/cookbooks/tempest/templates/default/run_filters/neutron.txt.erb
Labels: do not merge yet

#2383 [5.0] nova: Populate cinder SES settings early (SOC-11179)
  chef/cookbooks/nova/recipes/config.rb
Labels: backport from SOC9

#2378 [5.0] magnum: Add SSL support (SOC-9849)
  chef/cookbooks/magnum/attributes/default.rb
  chef/cookbooks/magnum/recipes/common.rb
  chef/cookbooks/magnum/templates/default/magnum.conf.erb
  chef/data_bags/crowbar/migrate/magnum/202_add_ssl_attributes.rb
  chef/data_bags/crowbar/template-magnum.json
  chef/data_bags/crowbar/template-magnum.schema
  crowbar_framework/app/helpers/barclamp/magnum_helper.rb
  crowbar_framework/app/views/barclamp/magnum/_edit_attributes.html.haml
  crowbar_framework/config/locales/magnum/en.yml
Labels: backport from SOC9
